### ISSUE TITLE
Policies reference

### ISSUE THREAD

**Issue by dreampost** [Azure/Enterprise-Scale-for-AKS#49]
I think this part is a bit misleading: "The policies applied by the platform foundation would trickle down to the Enterprise-scale for AKS landingzone subscription."
There is a "Platform" management group, but policies applied to the Platform management group are not inherited in the Landing zones management group.

**Comment by mosabami** [comment]
@dreampost  thanks for the tip. fixed. apologies for the delay the team bas had a busy last 4 weeks.
