### ISSUE TITLE
Impact of installing AKS add-ons which don't exist in Terraform

### ISSUE THREAD

**Issue by rishabhsaha** [Azure/Enterprise-Scale-for-AKS#54]
There are a few add-ons like azure pod identity, azure key vault csi driver secret store and similar which dont exist in Terraform. Request to document the impact of using those as part of the provisioning process. Ex - they would get deleted if the terraform script is run again etc.

**Comment by mosabami** [comment]
thanks @rishabhsaha  for your feedback. The warning has been added here: https://github.com/Azure/Enterprise-Scale-for-AKS/blob/main/Scenarios/Secure-Baseline/Terraform/07-b-keyvault-addon.md
