### ISSUE TITLE
Document the differences with AKS secure baseline

### ISSUE THREAD

**Issue by rishabhsaha** [Azure/Enterprise-Scale-for-AKS#55]
It would be helpful if we could document the exact set of differences with AKS secure baseline (Terraform, more modular etc.). The ask is important since customers might have already referred the secure baseline in some capacity as a starting point.

**Comment by mosabami** [comment]
@rishabhsaha  thanks for your feedback. Done: you can find it here: https://github.com/Azure/Enterprise-Scale-for-AKS/tree/main/Scenarios/Secure-Baseline
