### ISSUE TITLE
Mixed description for Container Registry Private Link and Key Vault Secret access

### ISSUE THREAD

**Issue by MarekLani** [Azure/Enterprise-Scale-for-AKS#93]
Descriptions in following sections are mixing keyvault and container registry resources:

https://github.com/Azure/Enterprise-Scale-for-AKS/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/08-workload.md#provide-yourself-access-to-create-secrets-in-your-key-vault

https://github.com/Azure/Enterprise-Scale-for-AKS/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/08-workload.md#provide-yourself-access-to-create-secrets-in-your-key-vault

**Comment by ArielRam99** [comment]
@mosabami I'll take this on.

**Comment by mosabami** [comment]
fix merged
